### ISSUE TITLE
Add web socket functionality to server

### ISSUE THREAD

**Issue by SanderMertens** [cortexlang/web#3]
For pushing realtime updates to a web client, the server will support web socket functionality. A protocol must be designed that supports creating subscriptions on objects. In the future, this protocol may be extended to support creating, updating and deleting objects.

- [x] setup web socket connection
- [x] handle object updates
- [x] handle new objects
- [x] handle deleted objects

### Protocol description

Message | Source | Format | Reply
------------ | ------------- | ------------- | -------------
Listen | Client | `L [flag[|flag...]] id` | `subscription-id`
Silence | Client | `S subscription-id` | `0` if ok, `-1` if error
New event | Server | `{'kind': 'new', 'id': subscription-id, 'observable': {'meta': {...}}}` | NA
Define event | Server | `{'kind': 'define', 'id': subscription-id, 'observable': {'meta': {...}, 'value': {...}}}` | NA
Update event | Server | `{'kind': 'update', 'id': subscription-id, 'observable': {'meta': {...}, 'value': {...}}}` | NA
Destruct event | Server | `{'kind': 'destruct', 'id': subscription-id, 'observable': {'meta': {...}}}` | NA

### Examples
Example | Message | Response
 ---- | ---- | ----
Listen for updates of `/a` | `L update /a` | `1`
Silence updates of `/a` | `S 1` | `0`
Listen for updates of children of `/a` | `L update|scope /a` | `2`

**Comment by jleeothon** [comment]
Can we elaborate on `flag`?
